valor = input('Digite algo: \n')
print('O tipo primitivo desse valor é ', type(valor))
print('Só tem espaços?', valor.isspace())
print('E um número?', valor.isnumeric())
print('O valor e alpha númerico?', valor.isalnum())
print('O valor e decimal?', valor.isdecimal())
print('E alfabetico?', valor.isalpha())
print('Está em letras maiusculas?', valor.isupper())
print('Está em letras minusculas?', valor.islower())
print('Está capitalizada?', valor.istitle())
